<?php

require_once "../model/ProjectModel.php";
require_once "HttpResource.php";

/**
 * Created by PhpStorm.
 * User: nillernoels
 * Date: 26/12/15
 * Time: 11:28
 */
class ProjectApi extends HttpResource
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     *  Return an associative array with limit of 4 rows from db
     *  the total count of rows is at the index 'count' in the array
     */
    protected function do_get()
    {
        if(isset($_GET['trainer-id']) && isset($_GET['page'])){
            $param1 = explode( "/", $_GET['trainer-id'] );
            $param2 = explode( "/", $_GET['page'] );
            $id = $param1[0];
            $currentPage = $param2[0];
            $rows = ProjectModel::getCurrentProjects($id, $currentPage, 4);
            $rows['totalProjects'] = count(ProjectModel::getAllProjects($id)); // add count of rows to the array
            $rows['currentPage'] = $currentPage;
            $this->statusCode = 200;
            // Produce utf8 encoded json
            $this->headers[] = "Content-type: text/json; charset=utf-8";
            $this->body = json_encode($rows);
        }
    }

}

ProjectApi::run();