<?php

require_once "../model/ProjectModel.php";
require_once "HttpResource.php";

/**
 * Created by PhpStorm.
 * User: nillernoels
 * Date: 26/12/15
 * Time: 11:28
 */
class ProjectApi extends HttpResource
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     *  Return an associative array with limit of 4 rows from db
     *  the total count of rows is at the index 'count' in the array
     */
    protected function do_get()
    {
        if(isset($_GET['trainer-id']) && isset($_GET['page'])){
            $param1 = explode( "/", $_GET['trainer-id'] );
            $param2 = explode( "/", $_GET['page'] );
            $id = $param1[0];
            $currentPage = $param2[0];
            $rows = ProjectModel::getCurrentProjects($id, $currentPage, 4);
            $rows['totalProjects'] = count(ProjectModel::getAllProjects($id)); // add count of rows to the array
            $rows['currentPage'] = $currentPage;
            $this->statusCode = 200;
            // Produce utf8 encoded json
            $this->headers[] = "Content-type: text/json; charset=utf-8";
            $this->body = json_encode($rows);
        }
    }

    protected function do_put()
    {
        parent::do_put(); // TODO: Change the autogenerated stub
        parse_str(file_get_contents("php://input"), $_PUT);
        if (empty($_PUT["title"])) {
            $this->exit_error(400, "titleMandatoryAndNotEmpty");
        }
        else{
            $title = $_PUT["title"];
            $date = '02/07/2016 12:00:00';    // to set deadline - maybe change this but it works -_-
            $date = preg_replace('#(\d{2})/(\d{2})/(\d{4})\s(.*)#', '$3-$2-$1 $4', $date);
            ProjectModel::updateProject($title, "test1",$date, 2);
            echo $title;
        }

    }

    protected function do_post()
    {
        parent::do_post(); // TODO: Change the autogenerated stub
        $var = $_POST["title"];
        echo $var;

    }

}

ProjectApi::run();