<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once("HttpResource.php");
require_once("../model/TeamModel.php");

/**
 * Created by PhpStorm.
 * User: nillernoels
 * Date: 23/12/15
 * Time: 10:43
 */
class TeamApi extends HttpResource
{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function do_get()
    {
        parent::do_get(); // TODO: Change the autogenerated stub
        TeamModel::addStudentToTeam(2,5);

    }

    protected function do_post()
    {
        parent::do_post(); // TODO: Change the autogenerated stub
    }

    protected function do_put()
    {
        parent::do_put(); // TODO: Change the autogenerated stub
    }

    protected function do_head()
    {

    }

    protected function do_delete()
    {
        parent::do_delete(); // TODO: Change the autogenerated stub
    }

}

TeamApi::run();